// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddThread(arg1) {
  return window['go']['app']['App']['AddThread'](arg1);
}

export function ArchiveThread(arg1, arg2) {
  return window['go']['app']['App']['ArchiveThread'](arg1, arg2);
}

export function CheckToken() {
  return window['go']['app']['App']['CheckToken']();
}

export function DeleteThread(arg1) {
  return window['go']['app']['App']['DeleteThread'](arg1);
}

export function DraftReply(arg1, arg2) {
  return window['go']['app']['App']['DraftReply'](arg1, arg2);
}

export function GetThread(arg1) {
  return window['go']['app']['App']['GetThread'](arg1);
}

export function ListThreads() {
  return window['go']['app']['App']['ListThreads']();
}

export function RefreshAll() {
  return window['go']['app']['App']['RefreshAll']();
}

export function RefreshThread(arg1) {
  return window['go']['app']['App']['RefreshThread'](arg1);
}

export function SaveToken(arg1) {
  return window['go']['app']['App']['SaveToken'](arg1);
}

export function SendReply(arg1, arg2) {
  return window['go']['app']['App']['SendReply'](arg1, arg2);
}

export function TokenStatus() {
  return window['go']['app']['App']['TokenStatus']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
