// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddThread(arg1:string):Promise<app.ThreadView>;

export function ArchiveThread(arg1:number,arg2:boolean):Promise<void>;

export function CheckToken():Promise<app.TokenStatus>;

export function DeleteThread(arg1:number):Promise<void>;

export function DraftReply(arg1:number,arg2:string):Promise<app.DraftView>;

export function GetThread(arg1:number):Promise<app.ThreadView>;

export function ListThreads():Promise<Array<app.ThreadItem>>;

export function RefreshAll():Promise<Array<app.RefreshOutcome>>;

export function RefreshThread(arg1:number):Promise<app.ThreadView>;

export function SaveToken(arg1:string):Promise<app.TokenStatus>;

export function SendReply(arg1:number,arg2:string):Promise<app.SentView>;

export function TokenStatus():Promise<app.TokenStatus>;

export function Version():Promise<string>;
